#!/bin/dash

#
# sb-dot
#

# I will strongly interpret the dot!

. sb-status2d

# Curl xml
query=$(curl -s https://gcpdot.com/gcpindex.php)
# Parse for first float
variance=$(echo $query | grep -Po '<s t=[^>]+>\K[^<]+' | head -1)
# Convert to 4 digit int
variance="$(expr substr "$variance" 3 $(expr length "$variance" - 5))"

if [ $variance -gt 9999 ]; then
    color="#24CBFD"
elif [ $variance -ge 9500 ]; then
    color="#0EEEFF"
elif [ $variance -ge 9300 ]; then
    color="#ACF2FF"
elif [ $variance -ge 9125 ]; then
    color="#64FAAB"
elif [ $variance -ge 9000 ]; then
    color="#64FA64"
elif [ $variance -ge 4000 ]; then
    color="#AEFA00"
elif [ $variance -ge 3000 ]; then
    color="#F9FA00"
elif [ $variance -ge 2300 ]; then
    color="#FFFA40"
elif [ $variance -ge 100 ]; then
    color="#FFD517"
elif [ $variance -ge 0500 ]; then
    color="#FFB82E"
elif [ $variance -ge 0100 ]; then
    color="#FF1E1E"
else
    color="#FFA8C0"
fi

printf "%s%s%s" "^c$color^" "" "$s2d_reset" && exit 0
