#!/bin/dash

#
# sb-emacsclient
#

. sb-status2d

status=$(emacsclient -a false -e 't')

if [ "$status" = 't' ]; then
    printf "%s%s %s" "$s2d_color3" "" "$s2d_reset" && exit 0
else
    exit 0
fi

