#!/bin/sh

#
# sb-emacsclient
#

source sb-status2d

status=$(emacsclient -a false -e 't')

if [ "$status" = 't' ]; then
    icon=""
else
    icon=""
fi

printf "%s" "$s2d_color3" "$icon" "$s2d_reset" && exit 0
