#!/bin/dash
# Description: Script to get current volume

. sb-status2d

info="$(amixer get Master | grep '%' | head -n1)"
percent="$(echo "$info" | sed -E 's/.*\[(.*)%\].*/\1/')"

if echo "$info" | grep -q 'off'; then
    icon_volume="󰖁"
elif [ "$percent" -lt 20 ]; then
    icon_volume=""
elif [ "$percent" -lt 60 ]; then
    icon_volume="󰕾"
else
    icon_volume=""
fi

printf "%s%s %s%%%s" "$s2d_color2" "$icon_volume" "$percent" "$s2d_reset" && exit 0
